# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule KeycloakAdminRESTAPI.Model.AccessTokenAuthorization do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"permissions"
  ]

  @type t :: %__MODULE__{
    :"permissions" => [KeycloakAdminRESTAPI.Model.Permission.t] | nil
  }
end

defimpl Poison.Decoder, for: KeycloakAdminRESTAPI.Model.AccessTokenAuthorization do
  import KeycloakAdminRESTAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"permissions", :list, KeycloakAdminRESTAPI.Model.Permission, options)
  end
end

