# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule KeycloakAdminRESTAPI.Model.AccessTokenAccess do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"roles",
    :"verify_caller"
  ]

  @type t :: %__MODULE__{
    :"roles" => [String.t] | nil,
    :"verify_caller" => boolean() | nil
  }
end

defimpl Poison.Decoder, for: KeycloakAdminRESTAPI.Model.AccessTokenAccess do
  def decode(value, _options) do
    value
  end
end

