# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule KeycloakAdminRESTAPI.Model.AuthenticationExecutionRepresentation do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"authenticator",
    :"authenticatorConfig",
    :"authenticatorFlow",
    :"flowId",
    :"id",
    :"parentFlow",
    :"priority",
    :"requirement"
  ]

  @type t :: %__MODULE__{
    :"authenticator" => String.t | nil,
    :"authenticatorConfig" => String.t | nil,
    :"authenticatorFlow" => boolean() | nil,
    :"flowId" => String.t | nil,
    :"id" => String.t | nil,
    :"parentFlow" => String.t | nil,
    :"priority" => integer() | nil,
    :"requirement" => String.t | nil
  }
end

defimpl Poison.Decoder, for: KeycloakAdminRESTAPI.Model.AuthenticationExecutionRepresentation do
  def decode(value, _options) do
    value
  end
end

