# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule KeycloakAdminRESTAPI.Model.AuthenticationExecutionExportRepresentation do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"authenticator",
    :"authenticatorConfig",
    :"authenticatorFlow",
    :"flowAlias",
    :"priority",
    :"requirement",
    :"userSetupAllowed"
  ]

  @type t :: %__MODULE__{
    :"authenticator" => String.t | nil,
    :"authenticatorConfig" => String.t | nil,
    :"authenticatorFlow" => boolean() | nil,
    :"flowAlias" => String.t | nil,
    :"priority" => integer() | nil,
    :"requirement" => String.t | nil,
    :"userSetupAllowed" => boolean() | nil
  }
end

defimpl Poison.Decoder, for: KeycloakAdminRESTAPI.Model.AuthenticationExecutionExportRepresentation do
  def decode(value, _options) do
    value
  end
end

