# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule KeycloakAdminRESTAPI.Model.AuthenticationFlowRepresentation do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"alias",
    :"authenticationExecutions",
    :"builtIn",
    :"description",
    :"id",
    :"providerId",
    :"topLevel"
  ]

  @type t :: %__MODULE__{
    :"alias" => String.t | nil,
    :"authenticationExecutions" => [KeycloakAdminRESTAPI.Model.AuthenticationExecutionExportRepresentation.t] | nil,
    :"builtIn" => boolean() | nil,
    :"description" => String.t | nil,
    :"id" => String.t | nil,
    :"providerId" => String.t | nil,
    :"topLevel" => boolean() | nil
  }
end

defimpl Poison.Decoder, for: KeycloakAdminRESTAPI.Model.AuthenticationFlowRepresentation do
  import KeycloakAdminRESTAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"authenticationExecutions", :list, KeycloakAdminRESTAPI.Model.AuthenticationExecutionExportRepresentation, options)
  end
end

