# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule KeycloakAdminRESTAPI.Model.AuthenticationExecutionInfoRepresentation do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"alias",
    :"authenticationConfig",
    :"authenticationFlow",
    :"configurable",
    :"description",
    :"displayName",
    :"flowId",
    :"id",
    :"index",
    :"level",
    :"providerId",
    :"requirement",
    :"requirementChoices"
  ]

  @type t :: %__MODULE__{
    :"alias" => String.t | nil,
    :"authenticationConfig" => String.t | nil,
    :"authenticationFlow" => boolean() | nil,
    :"configurable" => boolean() | nil,
    :"description" => String.t | nil,
    :"displayName" => String.t | nil,
    :"flowId" => String.t | nil,
    :"id" => String.t | nil,
    :"index" => integer() | nil,
    :"level" => integer() | nil,
    :"providerId" => String.t | nil,
    :"requirement" => String.t | nil,
    :"requirementChoices" => [String.t] | nil
  }
end

defimpl Poison.Decoder, for: KeycloakAdminRESTAPI.Model.AuthenticationExecutionInfoRepresentation do
  def decode(value, _options) do
    value
  end
end

