# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule KeycloakAdminRESTAPI.Model.CertificateRepresentation do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"certificate",
    :"kid",
    :"privateKey",
    :"publicKey"
  ]

  @type t :: %__MODULE__{
    :"certificate" => String.t | nil,
    :"kid" => String.t | nil,
    :"privateKey" => String.t | nil,
    :"publicKey" => String.t | nil
  }
end

defimpl Poison.Decoder, for: KeycloakAdminRESTAPI.Model.CertificateRepresentation do
  def decode(value, _options) do
    value
  end
end

