# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule KeycloakAdminRESTAPI.Model.ClientProfilesRepresentation do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"globalProfiles",
    :"profiles"
  ]

  @type t :: %__MODULE__{
    :"globalProfiles" => [KeycloakAdminRESTAPI.Model.ClientProfileRepresentation.t] | nil,
    :"profiles" => [KeycloakAdminRESTAPI.Model.ClientProfileRepresentation.t] | nil
  }
end

defimpl Poison.Decoder, for: KeycloakAdminRESTAPI.Model.ClientProfilesRepresentation do
  import KeycloakAdminRESTAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"globalProfiles", :list, KeycloakAdminRESTAPI.Model.ClientProfileRepresentation, options)
    |> deserialize(:"profiles", :list, KeycloakAdminRESTAPI.Model.ClientProfileRepresentation, options)
  end
end

