# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule KeycloakAdminRESTAPI.Model.ClientPolicyExecutorRepresentation do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"configuration",
    :"executor"
  ]

  @type t :: %__MODULE__{
    :"configuration" => KeycloakAdminRESTAPI.Model.JsonNode.t | nil,
    :"executor" => String.t | nil
  }
end

defimpl Poison.Decoder, for: KeycloakAdminRESTAPI.Model.ClientPolicyExecutorRepresentation do
  import KeycloakAdminRESTAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"configuration", :struct, KeycloakAdminRESTAPI.Model.JsonNode, options)
  end
end

