# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule KeycloakAdminRESTAPI.Model.ClientMappingsRepresentation do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"client",
    :"id",
    :"mappings"
  ]

  @type t :: %__MODULE__{
    :"client" => String.t | nil,
    :"id" => String.t | nil,
    :"mappings" => [KeycloakAdminRESTAPI.Model.RoleRepresentation.t] | nil
  }
end

defimpl Poison.Decoder, for: KeycloakAdminRESTAPI.Model.ClientMappingsRepresentation do
  import KeycloakAdminRESTAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"mappings", :list, KeycloakAdminRESTAPI.Model.RoleRepresentation, options)
  end
end

