# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule KeycloakAdminRESTAPI.Model.ClientScopeRepresentation do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"attributes",
    :"description",
    :"id",
    :"name",
    :"protocol",
    :"protocolMappers"
  ]

  @type t :: %__MODULE__{
    :"attributes" => %{optional(String.t) => map()} | nil,
    :"description" => String.t | nil,
    :"id" => String.t | nil,
    :"name" => String.t | nil,
    :"protocol" => String.t | nil,
    :"protocolMappers" => [KeycloakAdminRESTAPI.Model.ProtocolMapperRepresentation.t] | nil
  }
end

defimpl Poison.Decoder, for: KeycloakAdminRESTAPI.Model.ClientScopeRepresentation do
  import KeycloakAdminRESTAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"protocolMappers", :list, KeycloakAdminRESTAPI.Model.ProtocolMapperRepresentation, options)
  end
end

