# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule KeycloakAdminRESTAPI.Model.ClientPoliciesRepresentation do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"policies"
  ]

  @type t :: %__MODULE__{
    :"policies" => [KeycloakAdminRESTAPI.Model.ClientPolicyRepresentation.t] | nil
  }
end

defimpl Poison.Decoder, for: KeycloakAdminRESTAPI.Model.ClientPoliciesRepresentation do
  import KeycloakAdminRESTAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"policies", :list, KeycloakAdminRESTAPI.Model.ClientPolicyRepresentation, options)
  end
end

