# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule KeycloakAdminRESTAPI.Model.ClientInitialAccessCreatePresentation do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"count",
    :"expiration"
  ]

  @type t :: %__MODULE__{
    :"count" => integer() | nil,
    :"expiration" => integer() | nil
  }
end

defimpl Poison.Decoder, for: KeycloakAdminRESTAPI.Model.ClientInitialAccessCreatePresentation do
  def decode(value, _options) do
    value
  end
end

