# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule KeycloakAdminRESTAPI.Model.ClientInitialAccessPresentation do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"count",
    :"expiration",
    :"id",
    :"remainingCount",
    :"timestamp",
    :"token"
  ]

  @type t :: %__MODULE__{
    :"count" => integer() | nil,
    :"expiration" => integer() | nil,
    :"id" => String.t | nil,
    :"remainingCount" => integer() | nil,
    :"timestamp" => integer() | nil,
    :"token" => String.t | nil
  }
end

defimpl Poison.Decoder, for: KeycloakAdminRESTAPI.Model.ClientInitialAccessPresentation do
  def decode(value, _options) do
    value
  end
end

