# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule KeycloakAdminRESTAPI.Model.ClientPolicyRepresentation do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"conditions",
    :"description",
    :"enabled",
    :"name",
    :"profiles"
  ]

  @type t :: %__MODULE__{
    :"conditions" => [KeycloakAdminRESTAPI.Model.ClientPolicyConditionRepresentation.t] | nil,
    :"description" => String.t | nil,
    :"enabled" => boolean() | nil,
    :"name" => String.t | nil,
    :"profiles" => [String.t] | nil
  }
end

defimpl Poison.Decoder, for: KeycloakAdminRESTAPI.Model.ClientPolicyRepresentation do
  import KeycloakAdminRESTAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"conditions", :list, KeycloakAdminRESTAPI.Model.ClientPolicyConditionRepresentation, options)
  end
end

