# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule KeycloakAdminRESTAPI.Model.ConfigPropertyRepresentation do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"defaultValue",
    :"helpText",
    :"label",
    :"name",
    :"options",
    :"secret",
    :"type"
  ]

  @type t :: %__MODULE__{
    :"defaultValue" => map() | nil,
    :"helpText" => String.t | nil,
    :"label" => String.t | nil,
    :"name" => String.t | nil,
    :"options" => [String.t] | nil,
    :"secret" => boolean() | nil,
    :"type" => String.t | nil
  }
end

defimpl Poison.Decoder, for: KeycloakAdminRESTAPI.Model.ConfigPropertyRepresentation do
  def decode(value, _options) do
    value
  end
end

