# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule KeycloakAdminRESTAPI.Model.CredentialRepresentation do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"createdDate",
    :"credentialData",
    :"id",
    :"priority",
    :"secretData",
    :"temporary",
    :"type",
    :"userLabel",
    :"value"
  ]

  @type t :: %__MODULE__{
    :"createdDate" => integer() | nil,
    :"credentialData" => String.t | nil,
    :"id" => String.t | nil,
    :"priority" => integer() | nil,
    :"secretData" => String.t | nil,
    :"temporary" => boolean() | nil,
    :"type" => String.t | nil,
    :"userLabel" => String.t | nil,
    :"value" => String.t | nil
  }
end

defimpl Poison.Decoder, for: KeycloakAdminRESTAPI.Model.CredentialRepresentation do
  def decode(value, _options) do
    value
  end
end

