# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule KeycloakAdminRESTAPI.Model.FederatedIdentityRepresentation do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"identityProvider",
    :"userId",
    :"userName"
  ]

  @type t :: %__MODULE__{
    :"identityProvider" => String.t | nil,
    :"userId" => String.t | nil,
    :"userName" => String.t | nil
  }
end

defimpl Poison.Decoder, for: KeycloakAdminRESTAPI.Model.FederatedIdentityRepresentation do
  def decode(value, _options) do
    value
  end
end

