# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule KeycloakAdminRESTAPI.Model.GroupRepresentation do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"access",
    :"attributes",
    :"clientRoles",
    :"id",
    :"name",
    :"path",
    :"realmRoles",
    :"subGroups"
  ]

  @type t :: %__MODULE__{
    :"access" => %{optional(String.t) => map()} | nil,
    :"attributes" => %{optional(String.t) => map()} | nil,
    :"clientRoles" => %{optional(String.t) => map()} | nil,
    :"id" => String.t | nil,
    :"name" => String.t | nil,
    :"path" => String.t | nil,
    :"realmRoles" => [String.t] | nil,
    :"subGroups" => [KeycloakAdminRESTAPI.Model.GroupRepresentation.t] | nil
  }
end

defimpl Poison.Decoder, for: KeycloakAdminRESTAPI.Model.GroupRepresentation do
  import KeycloakAdminRESTAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"subGroups", :list, KeycloakAdminRESTAPI.Model.GroupRepresentation, options)
  end
end

