# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule KeycloakAdminRESTAPI.Model.IdToken do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"acr",
    :"address",
    :"at_hash",
    :"auth_time",
    :"azp",
    :"birthdate",
    :"c_hash",
    :"category",
    :"claims_locales",
    :"email",
    :"email_verified",
    :"exp",
    :"family_name",
    :"gender",
    :"given_name",
    :"iat",
    :"iss",
    :"jti",
    :"locale",
    :"middle_name",
    :"name",
    :"nbf",
    :"nickname",
    :"nonce",
    :"otherClaims",
    :"phone_number",
    :"phone_number_verified",
    :"picture",
    :"preferred_username",
    :"profile",
    :"s_hash",
    :"session_state",
    :"sid",
    :"sub",
    :"typ",
    :"updated_at",
    :"website",
    :"zoneinfo"
  ]

  @type t :: %__MODULE__{
    :"acr" => String.t | nil,
    :"address" => KeycloakAdminRESTAPI.Model.AddressClaimSet.t | nil,
    :"at_hash" => String.t | nil,
    :"auth_time" => integer() | nil,
    :"azp" => String.t | nil,
    :"birthdate" => String.t | nil,
    :"c_hash" => String.t | nil,
    :"category" => String.t | nil,
    :"claims_locales" => String.t | nil,
    :"email" => String.t | nil,
    :"email_verified" => boolean() | nil,
    :"exp" => integer() | nil,
    :"family_name" => String.t | nil,
    :"gender" => String.t | nil,
    :"given_name" => String.t | nil,
    :"iat" => integer() | nil,
    :"iss" => String.t | nil,
    :"jti" => String.t | nil,
    :"locale" => String.t | nil,
    :"middle_name" => String.t | nil,
    :"name" => String.t | nil,
    :"nbf" => integer() | nil,
    :"nickname" => String.t | nil,
    :"nonce" => String.t | nil,
    :"otherClaims" => %{optional(String.t) => map()} | nil,
    :"phone_number" => String.t | nil,
    :"phone_number_verified" => boolean() | nil,
    :"picture" => String.t | nil,
    :"preferred_username" => String.t | nil,
    :"profile" => String.t | nil,
    :"s_hash" => String.t | nil,
    :"session_state" => String.t | nil,
    :"sid" => String.t | nil,
    :"sub" => String.t | nil,
    :"typ" => String.t | nil,
    :"updated_at" => integer() | nil,
    :"website" => String.t | nil,
    :"zoneinfo" => String.t | nil
  }
end

defimpl Poison.Decoder, for: KeycloakAdminRESTAPI.Model.IdToken do
  import KeycloakAdminRESTAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"address", :struct, KeycloakAdminRESTAPI.Model.AddressClaimSet, options)
  end
end

