# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule KeycloakAdminRESTAPI.Model.IdentityProviderRepresentation do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"addReadTokenRoleOnCreate",
    :"alias",
    :"config",
    :"displayName",
    :"enabled",
    :"firstBrokerLoginFlowAlias",
    :"internalId",
    :"linkOnly",
    :"postBrokerLoginFlowAlias",
    :"providerId",
    :"storeToken",
    :"trustEmail"
  ]

  @type t :: %__MODULE__{
    :"addReadTokenRoleOnCreate" => boolean() | nil,
    :"alias" => String.t | nil,
    :"config" => %{optional(String.t) => map()} | nil,
    :"displayName" => String.t | nil,
    :"enabled" => boolean() | nil,
    :"firstBrokerLoginFlowAlias" => String.t | nil,
    :"internalId" => String.t | nil,
    :"linkOnly" => boolean() | nil,
    :"postBrokerLoginFlowAlias" => String.t | nil,
    :"providerId" => String.t | nil,
    :"storeToken" => boolean() | nil,
    :"trustEmail" => boolean() | nil
  }
end

defimpl Poison.Decoder, for: KeycloakAdminRESTAPI.Model.IdentityProviderRepresentation do
  def decode(value, _options) do
    value
  end
end

