# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule KeycloakAdminRESTAPI.Model.JsonNode do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"array",
    :"bigDecimal",
    :"bigInteger",
    :"binary",
    :"boolean",
    :"containerNode",
    :"double",
    :"empty",
    :"float",
    :"floatingPointNumber",
    :"int",
    :"integralNumber",
    :"long",
    :"missingNode",
    :"nodeType",
    :"null",
    :"number",
    :"object",
    :"pojo",
    :"short",
    :"textual",
    :"valueNode"
  ]

  @type t :: %__MODULE__{
    :"array" => boolean() | nil,
    :"bigDecimal" => boolean() | nil,
    :"bigInteger" => boolean() | nil,
    :"binary" => boolean() | nil,
    :"boolean" => boolean() | nil,
    :"containerNode" => boolean() | nil,
    :"double" => boolean() | nil,
    :"empty" => boolean() | nil,
    :"float" => boolean() | nil,
    :"floatingPointNumber" => boolean() | nil,
    :"int" => boolean() | nil,
    :"integralNumber" => boolean() | nil,
    :"long" => boolean() | nil,
    :"missingNode" => boolean() | nil,
    :"nodeType" => String.t | nil,
    :"null" => boolean() | nil,
    :"number" => boolean() | nil,
    :"object" => boolean() | nil,
    :"pojo" => boolean() | nil,
    :"short" => boolean() | nil,
    :"textual" => boolean() | nil,
    :"valueNode" => boolean() | nil
  }
end

defimpl Poison.Decoder, for: KeycloakAdminRESTAPI.Model.JsonNode do
  def decode(value, _options) do
    value
  end
end

