# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule KeycloakAdminRESTAPI.Model.KeysMetadataRepresentationKeyMetadataRepresentation do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"algorithm",
    :"certificate",
    :"kid",
    :"providerId",
    :"providerPriority",
    :"publicKey",
    :"status",
    :"type",
    :"use"
  ]

  @type t :: %__MODULE__{
    :"algorithm" => String.t | nil,
    :"certificate" => String.t | nil,
    :"kid" => String.t | nil,
    :"providerId" => String.t | nil,
    :"providerPriority" => integer() | nil,
    :"publicKey" => String.t | nil,
    :"status" => String.t | nil,
    :"type" => String.t | nil,
    :"use" => String.t | nil
  }
end

defimpl Poison.Decoder, for: KeycloakAdminRESTAPI.Model.KeysMetadataRepresentationKeyMetadataRepresentation do
  def decode(value, _options) do
    value
  end
end

