# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule KeycloakAdminRESTAPI.Model.KeysMetadataRepresentation do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"active",
    :"keys"
  ]

  @type t :: %__MODULE__{
    :"active" => %{optional(String.t) => map()} | nil,
    :"keys" => [KeycloakAdminRESTAPI.Model.KeysMetadataRepresentationKeyMetadataRepresentation.t] | nil
  }
end

defimpl Poison.Decoder, for: KeycloakAdminRESTAPI.Model.KeysMetadataRepresentation do
  import KeycloakAdminRESTAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"keys", :list, KeycloakAdminRESTAPI.Model.KeysMetadataRepresentationKeyMetadataRepresentation, options)
  end
end

