# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule KeycloakAdminRESTAPI.Model.ManagementPermissionReference do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"enabled",
    :"resource",
    :"scopePermissions"
  ]

  @type t :: %__MODULE__{
    :"enabled" => boolean() | nil,
    :"resource" => String.t | nil,
    :"scopePermissions" => %{optional(String.t) => map()} | nil
  }
end

defimpl Poison.Decoder, for: KeycloakAdminRESTAPI.Model.ManagementPermissionReference do
  def decode(value, _options) do
    value
  end
end

