# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule KeycloakAdminRESTAPI.Model.MappingsRepresentation do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"clientMappings",
    :"realmMappings"
  ]

  @type t :: %__MODULE__{
    :"clientMappings" => %{optional(String.t) => map()} | nil,
    :"realmMappings" => [KeycloakAdminRESTAPI.Model.RoleRepresentation.t] | nil
  }
end

defimpl Poison.Decoder, for: KeycloakAdminRESTAPI.Model.MappingsRepresentation do
  import KeycloakAdminRESTAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"realmMappings", :list, KeycloakAdminRESTAPI.Model.RoleRepresentation, options)
  end
end

