# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule KeycloakAdminRESTAPI.Model.MemoryInfoRepresentation do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"free",
    :"freeFormated",
    :"freePercentage",
    :"total",
    :"totalFormated",
    :"used",
    :"usedFormated"
  ]

  @type t :: %__MODULE__{
    :"free" => integer() | nil,
    :"freeFormated" => String.t | nil,
    :"freePercentage" => integer() | nil,
    :"total" => integer() | nil,
    :"totalFormated" => String.t | nil,
    :"used" => integer() | nil,
    :"usedFormated" => String.t | nil
  }
end

defimpl Poison.Decoder, for: KeycloakAdminRESTAPI.Model.MemoryInfoRepresentation do
  def decode(value, _options) do
    value
  end
end

