# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule KeycloakAdminRESTAPI.Model.MultivaluedHashMap do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"empty",
    :"loadFactor",
    :"threshold"
  ]

  @type t :: %__MODULE__{
    :"empty" => boolean() | nil,
    :"loadFactor" => float() | nil,
    :"threshold" => integer() | nil
  }
end

defimpl Poison.Decoder, for: KeycloakAdminRESTAPI.Model.MultivaluedHashMap do
  def decode(value, _options) do
    value
  end
end

