# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule KeycloakAdminRESTAPI.Model.Permission do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"claims",
    :"rsid",
    :"rsname",
    :"scopes"
  ]

  @type t :: %__MODULE__{
    :"claims" => %{optional(String.t) => map()} | nil,
    :"rsid" => String.t | nil,
    :"rsname" => String.t | nil,
    :"scopes" => [String.t] | nil
  }
end

defimpl Poison.Decoder, for: KeycloakAdminRESTAPI.Model.Permission do
  def decode(value, _options) do
    value
  end
end

