# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule KeycloakAdminRESTAPI.Model.ProfileInfoRepresentation do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"disabledFeatures",
    :"experimentalFeatures",
    :"name",
    :"previewFeatures"
  ]

  @type t :: %__MODULE__{
    :"disabledFeatures" => [String.t] | nil,
    :"experimentalFeatures" => [String.t] | nil,
    :"name" => String.t | nil,
    :"previewFeatures" => [String.t] | nil
  }
end

defimpl Poison.Decoder, for: KeycloakAdminRESTAPI.Model.ProfileInfoRepresentation do
  def decode(value, _options) do
    value
  end
end

