# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule KeycloakAdminRESTAPI.Model.ProviderRepresentation do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"operationalInfo",
    :"order"
  ]

  @type t :: %__MODULE__{
    :"operationalInfo" => %{optional(String.t) => map()} | nil,
    :"order" => integer() | nil
  }
end

defimpl Poison.Decoder, for: KeycloakAdminRESTAPI.Model.ProviderRepresentation do
  def decode(value, _options) do
    value
  end
end

