# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule KeycloakAdminRESTAPI.Model.RealmEventsConfigRepresentation do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"adminEventsDetailsEnabled",
    :"adminEventsEnabled",
    :"enabledEventTypes",
    :"eventsEnabled",
    :"eventsExpiration",
    :"eventsListeners"
  ]

  @type t :: %__MODULE__{
    :"adminEventsDetailsEnabled" => boolean() | nil,
    :"adminEventsEnabled" => boolean() | nil,
    :"enabledEventTypes" => [String.t] | nil,
    :"eventsEnabled" => boolean() | nil,
    :"eventsExpiration" => integer() | nil,
    :"eventsListeners" => [String.t] | nil
  }
end

defimpl Poison.Decoder, for: KeycloakAdminRESTAPI.Model.RealmEventsConfigRepresentation do
  def decode(value, _options) do
    value
  end
end

