# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule KeycloakAdminRESTAPI.Model.ResourceServerRepresentation do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"allowRemoteResourceManagement",
    :"clientId",
    :"decisionStrategy",
    :"id",
    :"name",
    :"policies",
    :"policyEnforcementMode",
    :"resources",
    :"scopes"
  ]

  @type t :: %__MODULE__{
    :"allowRemoteResourceManagement" => boolean() | nil,
    :"clientId" => String.t | nil,
    :"decisionStrategy" => String.t | nil,
    :"id" => String.t | nil,
    :"name" => String.t | nil,
    :"policies" => [KeycloakAdminRESTAPI.Model.PolicyRepresentation.t] | nil,
    :"policyEnforcementMode" => String.t | nil,
    :"resources" => [KeycloakAdminRESTAPI.Model.ResourceRepresentation.t] | nil,
    :"scopes" => [KeycloakAdminRESTAPI.Model.ScopeRepresentation.t] | nil
  }
end

defimpl Poison.Decoder, for: KeycloakAdminRESTAPI.Model.ResourceServerRepresentation do
  import KeycloakAdminRESTAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"policies", :list, KeycloakAdminRESTAPI.Model.PolicyRepresentation, options)
    |> deserialize(:"resources", :list, KeycloakAdminRESTAPI.Model.ResourceRepresentation, options)
    |> deserialize(:"scopes", :list, KeycloakAdminRESTAPI.Model.ScopeRepresentation, options)
  end
end

