# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule KeycloakAdminRESTAPI.Model.ResourceRepresentation do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"id",
    :"attributes",
    :"displayName",
    :"icon_uri",
    :"name",
    :"ownerManagedAccess",
    :"scopes",
    :"type",
    :"uris"
  ]

  @type t :: %__MODULE__{
    :"id" => String.t | nil,
    :"attributes" => %{optional(String.t) => map()} | nil,
    :"displayName" => String.t | nil,
    :"icon_uri" => String.t | nil,
    :"name" => String.t | nil,
    :"ownerManagedAccess" => boolean() | nil,
    :"scopes" => [KeycloakAdminRESTAPI.Model.ScopeRepresentation.t] | nil,
    :"type" => String.t | nil,
    :"uris" => [String.t] | nil
  }
end

defimpl Poison.Decoder, for: KeycloakAdminRESTAPI.Model.ResourceRepresentation do
  import KeycloakAdminRESTAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"scopes", :list, KeycloakAdminRESTAPI.Model.ScopeRepresentation, options)
  end
end

