# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule KeycloakAdminRESTAPI.Model.RoleRepresentationComposites do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"client",
    :"realm"
  ]

  @type t :: %__MODULE__{
    :"client" => %{optional(String.t) => map()} | nil,
    :"realm" => [String.t] | nil
  }
end

defimpl Poison.Decoder, for: KeycloakAdminRESTAPI.Model.RoleRepresentationComposites do
  def decode(value, _options) do
    value
  end
end

