# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule KeycloakAdminRESTAPI.Model.RoleRepresentation do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"attributes",
    :"clientRole",
    :"composite",
    :"composites",
    :"containerId",
    :"description",
    :"id",
    :"name"
  ]

  @type t :: %__MODULE__{
    :"attributes" => %{optional(String.t) => map()} | nil,
    :"clientRole" => boolean() | nil,
    :"composite" => boolean() | nil,
    :"composites" => KeycloakAdminRESTAPI.Model.RoleRepresentationComposites.t | nil,
    :"containerId" => String.t | nil,
    :"description" => String.t | nil,
    :"id" => String.t | nil,
    :"name" => String.t | nil
  }
end

defimpl Poison.Decoder, for: KeycloakAdminRESTAPI.Model.RoleRepresentation do
  import KeycloakAdminRESTAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"composites", :struct, KeycloakAdminRESTAPI.Model.RoleRepresentationComposites, options)
  end
end

