# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule KeycloakAdminRESTAPI.Model.RolesRepresentation do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"client",
    :"realm"
  ]

  @type t :: %__MODULE__{
    :"client" => %{optional(String.t) => map()} | nil,
    :"realm" => [KeycloakAdminRESTAPI.Model.RoleRepresentation.t] | nil
  }
end

defimpl Poison.Decoder, for: KeycloakAdminRESTAPI.Model.RolesRepresentation do
  import KeycloakAdminRESTAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"realm", :list, KeycloakAdminRESTAPI.Model.RoleRepresentation, options)
  end
end

