# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule KeycloakAdminRESTAPI.Model.ServerInfoRepresentation do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"builtinProtocolMappers",
    :"clientImporters",
    :"clientInstallations",
    :"componentTypes",
    :"enums",
    :"identityProviders",
    :"memoryInfo",
    :"passwordPolicies",
    :"profileInfo",
    :"protocolMapperTypes",
    :"providers",
    :"socialProviders",
    :"systemInfo",
    :"themes"
  ]

  @type t :: %__MODULE__{
    :"builtinProtocolMappers" => %{optional(String.t) => map()} | nil,
    :"clientImporters" => [%{optional(String.t) => map()}] | nil,
    :"clientInstallations" => %{optional(String.t) => map()} | nil,
    :"componentTypes" => %{optional(String.t) => map()} | nil,
    :"enums" => %{optional(String.t) => map()} | nil,
    :"identityProviders" => [%{optional(String.t) => map()}] | nil,
    :"memoryInfo" => KeycloakAdminRESTAPI.Model.MemoryInfoRepresentation.t | nil,
    :"passwordPolicies" => [KeycloakAdminRESTAPI.Model.PasswordPolicyTypeRepresentation.t] | nil,
    :"profileInfo" => KeycloakAdminRESTAPI.Model.ProfileInfoRepresentation.t | nil,
    :"protocolMapperTypes" => %{optional(String.t) => map()} | nil,
    :"providers" => %{optional(String.t) => map()} | nil,
    :"socialProviders" => [%{optional(String.t) => map()}] | nil,
    :"systemInfo" => KeycloakAdminRESTAPI.Model.SystemInfoRepresentation.t | nil,
    :"themes" => %{optional(String.t) => map()} | nil
  }
end

defimpl Poison.Decoder, for: KeycloakAdminRESTAPI.Model.ServerInfoRepresentation do
  import KeycloakAdminRESTAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"memoryInfo", :struct, KeycloakAdminRESTAPI.Model.MemoryInfoRepresentation, options)
    |> deserialize(:"passwordPolicies", :list, KeycloakAdminRESTAPI.Model.PasswordPolicyTypeRepresentation, options)
    |> deserialize(:"profileInfo", :struct, KeycloakAdminRESTAPI.Model.ProfileInfoRepresentation, options)
    |> deserialize(:"systemInfo", :struct, KeycloakAdminRESTAPI.Model.SystemInfoRepresentation, options)
  end
end

