# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule KeycloakAdminRESTAPI.Model.SpiInfoRepresentation do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"internal",
    :"providers"
  ]

  @type t :: %__MODULE__{
    :"internal" => boolean() | nil,
    :"providers" => %{optional(String.t) => map()} | nil
  }
end

defimpl Poison.Decoder, for: KeycloakAdminRESTAPI.Model.SpiInfoRepresentation do
  def decode(value, _options) do
    value
  end
end

