# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule KeycloakAdminRESTAPI.Model.SystemInfoRepresentation do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"fileEncoding",
    :"javaHome",
    :"javaRuntime",
    :"javaVendor",
    :"javaVersion",
    :"javaVm",
    :"javaVmVersion",
    :"osArchitecture",
    :"osName",
    :"osVersion",
    :"serverTime",
    :"uptime",
    :"uptimeMillis",
    :"userDir",
    :"userLocale",
    :"userName",
    :"userTimezone",
    :"version"
  ]

  @type t :: %__MODULE__{
    :"fileEncoding" => String.t | nil,
    :"javaHome" => String.t | nil,
    :"javaRuntime" => String.t | nil,
    :"javaVendor" => String.t | nil,
    :"javaVersion" => String.t | nil,
    :"javaVm" => String.t | nil,
    :"javaVmVersion" => String.t | nil,
    :"osArchitecture" => String.t | nil,
    :"osName" => String.t | nil,
    :"osVersion" => String.t | nil,
    :"serverTime" => String.t | nil,
    :"uptime" => String.t | nil,
    :"uptimeMillis" => integer() | nil,
    :"userDir" => String.t | nil,
    :"userLocale" => String.t | nil,
    :"userName" => String.t | nil,
    :"userTimezone" => String.t | nil,
    :"version" => String.t | nil
  }
end

defimpl Poison.Decoder, for: KeycloakAdminRESTAPI.Model.SystemInfoRepresentation do
  def decode(value, _options) do
    value
  end
end

