# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule KeycloakAdminRESTAPI.Model.TestLdapConnectionRepresentation do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"action",
    :"authType",
    :"bindCredential",
    :"bindDn",
    :"componentId",
    :"connectionTimeout",
    :"connectionUrl",
    :"startTls",
    :"useTruststoreSpi"
  ]

  @type t :: %__MODULE__{
    :"action" => String.t | nil,
    :"authType" => String.t | nil,
    :"bindCredential" => String.t | nil,
    :"bindDn" => String.t | nil,
    :"componentId" => String.t | nil,
    :"connectionTimeout" => String.t | nil,
    :"connectionUrl" => String.t | nil,
    :"startTls" => String.t | nil,
    :"useTruststoreSpi" => String.t | nil
  }
end

defimpl Poison.Decoder, for: KeycloakAdminRESTAPI.Model.TestLdapConnectionRepresentation do
  def decode(value, _options) do
    value
  end
end

