# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule KeycloakAdminRESTAPI.Model.UserFederationProviderRepresentation do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"changedSyncPeriod",
    :"config",
    :"displayName",
    :"fullSyncPeriod",
    :"id",
    :"lastSync",
    :"priority",
    :"providerName"
  ]

  @type t :: %__MODULE__{
    :"changedSyncPeriod" => integer() | nil,
    :"config" => %{optional(String.t) => map()} | nil,
    :"displayName" => String.t | nil,
    :"fullSyncPeriod" => integer() | nil,
    :"id" => String.t | nil,
    :"lastSync" => integer() | nil,
    :"priority" => integer() | nil,
    :"providerName" => String.t | nil
  }
end

defimpl Poison.Decoder, for: KeycloakAdminRESTAPI.Model.UserFederationProviderRepresentation do
  def decode(value, _options) do
    value
  end
end

