# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule KeycloakAdminRESTAPI.Model.UserFederationMapperRepresentation do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"config",
    :"federationMapperType",
    :"federationProviderDisplayName",
    :"id",
    :"name"
  ]

  @type t :: %__MODULE__{
    :"config" => %{optional(String.t) => map()} | nil,
    :"federationMapperType" => String.t | nil,
    :"federationProviderDisplayName" => String.t | nil,
    :"id" => String.t | nil,
    :"name" => String.t | nil
  }
end

defimpl Poison.Decoder, for: KeycloakAdminRESTAPI.Model.UserFederationMapperRepresentation do
  def decode(value, _options) do
    value
  end
end

