# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule KeycloakAdminRESTAPI.Api.ClientInitialAccess do
  @moduledoc """
  API calls for all endpoints tagged `ClientInitialAccess`.
  """

  alias KeycloakAdminRESTAPI.Connection
  import KeycloakAdminRESTAPI.RequestBuilder


  @doc """

  ## Parameters

  - connection (KeycloakAdminRESTAPI.Connection): Connection to server
  - realm (String.t): realm name (not id!)
  - opts (KeywordList): [optional] Optional parameters
  ## Returns

  {:ok, [%Map{}, ...]} on success
  {:error, Tesla.Env.t} on failure
  """
  @spec realm_clients_initial_access_get(Tesla.Env.client, String.t, keyword()) :: {:ok, list(Map.t)} | {:error, Tesla.Env.t}
  def realm_clients_initial_access_get(connection, realm, _opts \\ []) do
    %{}
    |> method(:get)
    |> url("/#{realm}/clients-initial-access")
    |> Enum.into([])
    |> (&Connection.request(connection, &1)).()
    |> evaluate_response([
      { "2XX", []}
    ])
  end

  @doc """

  ## Parameters

  - connection (KeycloakAdminRESTAPI.Connection): Connection to server
  - realm (String.t): realm name (not id!)
  - id (String.t): 
  - opts (KeywordList): [optional] Optional parameters
  ## Returns

  {:ok, nil} on success
  {:error, Tesla.Env.t} on failure
  """
  @spec realm_clients_initial_access_id_delete(Tesla.Env.client, String.t, String.t, keyword()) :: {:ok, nil} | {:error, Tesla.Env.t}
  def realm_clients_initial_access_id_delete(connection, realm, id, _opts \\ []) do
    %{}
    |> method(:delete)
    |> url("/#{realm}/clients-initial-access/#{id}")
    |> Enum.into([])
    |> (&Connection.request(connection, &1)).()
    |> evaluate_response([
      { "2XX", false}
    ])
  end

  @doc """
  Create a new initial access token.

  ## Parameters

  - connection (KeycloakAdminRESTAPI.Connection): Connection to server
  - realm (String.t): realm name (not id!)
  - client_initial_access_create_presentation (ClientInitialAccessCreatePresentation): 
  - opts (KeywordList): [optional] Optional parameters
  ## Returns

  {:ok, KeycloakAdminRESTAPI.Model.ClientInitialAccessPresentation.t} on success
  {:error, Tesla.Env.t} on failure
  """
  @spec realm_clients_initial_access_post(Tesla.Env.client, String.t, KeycloakAdminRESTAPI.Model.ClientInitialAccessCreatePresentation.t, keyword()) :: {:ok, KeycloakAdminRESTAPI.Model.ClientInitialAccessPresentation.t} | {:error, Tesla.Env.t}
  def realm_clients_initial_access_post(connection, realm, client_initial_access_create_presentation, _opts \\ []) do
    %{}
    |> method(:post)
    |> url("/#{realm}/clients-initial-access")
    |> add_param(:body, :body, client_initial_access_create_presentation)
    |> Enum.into([])
    |> (&Connection.request(connection, &1)).()
    |> evaluate_response([
      { "2XX", %KeycloakAdminRESTAPI.Model.ClientInitialAccessPresentation{}}
    ])
  end
end
