# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule KeycloakAdminRESTAPI.Api.ClientRoleMappings do
  @moduledoc """
  API calls for all endpoints tagged `ClientRoleMappings`.
  """

  alias KeycloakAdminRESTAPI.Connection
  import KeycloakAdminRESTAPI.RequestBuilder


  @doc """
  Get available client-level roles that can be mapped to the user

  ## Parameters

  - connection (KeycloakAdminRESTAPI.Connection): Connection to server
  - realm (String.t): realm name (not id!)
  - id (String.t): 
  - client (String.t): 
  - opts (KeywordList): [optional] Optional parameters
  ## Returns

  {:ok, [%Map{}, ...]} on success
  {:error, Tesla.Env.t} on failure
  """
  @spec realm_groups_id_role_mappings_clients_client_available_get(Tesla.Env.client, String.t, String.t, String.t, keyword()) :: {:ok, list(Map.t)} | {:error, Tesla.Env.t}
  def realm_groups_id_role_mappings_clients_client_available_get(connection, realm, id, client, _opts \\ []) do
    %{}
    |> method(:get)
    |> url("/#{realm}/groups/#{id}/role-mappings/clients/#{client}/available")
    |> Enum.into([])
    |> (&Connection.request(connection, &1)).()
    |> evaluate_response([
      { "2XX", []}
    ])
  end

  @doc """
  Get effective client-level role mappings   This recurses any composite roles

  ## Parameters

  - connection (KeycloakAdminRESTAPI.Connection): Connection to server
  - realm (String.t): realm name (not id!)
  - id (String.t): 
  - client (String.t): 
  - opts (KeywordList): [optional] Optional parameters
    - :brief_representation (boolean()): if false, return roles with their attributes
  ## Returns

  {:ok, [%Map{}, ...]} on success
  {:error, Tesla.Env.t} on failure
  """
  @spec realm_groups_id_role_mappings_clients_client_composite_get(Tesla.Env.client, String.t, String.t, String.t, keyword()) :: {:ok, list(Map.t)} | {:error, Tesla.Env.t}
  def realm_groups_id_role_mappings_clients_client_composite_get(connection, realm, id, client, opts \\ []) do
    optional_params = %{
      :"briefRepresentation" => :query
    }
    %{}
    |> method(:get)
    |> url("/#{realm}/groups/#{id}/role-mappings/clients/#{client}/composite")
    |> add_optional_params(optional_params, opts)
    |> Enum.into([])
    |> (&Connection.request(connection, &1)).()
    |> evaluate_response([
      { "2XX", []}
    ])
  end

  @doc """
  Delete client-level roles from user role mapping

  ## Parameters

  - connection (KeycloakAdminRESTAPI.Connection): Connection to server
  - realm (String.t): realm name (not id!)
  - id (String.t): 
  - client (String.t): 
  - role_representation ([KeycloakAdminRESTAPI.Model.RoleRepresentation.t]): 
  - opts (KeywordList): [optional] Optional parameters
  ## Returns

  {:ok, nil} on success
  {:error, Tesla.Env.t} on failure
  """
  @spec realm_groups_id_role_mappings_clients_client_delete(Tesla.Env.client, String.t, String.t, String.t, list(KeycloakAdminRESTAPI.Model.RoleRepresentation.t), keyword()) :: {:ok, nil} | {:error, Tesla.Env.t}
  def realm_groups_id_role_mappings_clients_client_delete(connection, realm, id, client, role_representation, _opts \\ []) do
    %{}
    |> method(:delete)
    |> url("/#{realm}/groups/#{id}/role-mappings/clients/#{client}")
    |> add_param(:body, :body, role_representation)
    |> Enum.into([])
    |> (&Connection.request(connection, &1)).()
    |> evaluate_response([
      { "2XX", false}
    ])
  end

  @doc """
  Get client-level role mappings for the user, and the app

  ## Parameters

  - connection (KeycloakAdminRESTAPI.Connection): Connection to server
  - realm (String.t): realm name (not id!)
  - id (String.t): 
  - client (String.t): 
  - opts (KeywordList): [optional] Optional parameters
  ## Returns

  {:ok, [%Map{}, ...]} on success
  {:error, Tesla.Env.t} on failure
  """
  @spec realm_groups_id_role_mappings_clients_client_get(Tesla.Env.client, String.t, String.t, String.t, keyword()) :: {:ok, list(Map.t)} | {:error, Tesla.Env.t}
  def realm_groups_id_role_mappings_clients_client_get(connection, realm, id, client, _opts \\ []) do
    %{}
    |> method(:get)
    |> url("/#{realm}/groups/#{id}/role-mappings/clients/#{client}")
    |> Enum.into([])
    |> (&Connection.request(connection, &1)).()
    |> evaluate_response([
      { "2XX", []}
    ])
  end

  @doc """
  Add client-level roles to the user role mapping

  ## Parameters

  - connection (KeycloakAdminRESTAPI.Connection): Connection to server
  - realm (String.t): realm name (not id!)
  - id (String.t): 
  - client (String.t): 
  - role_representation ([KeycloakAdminRESTAPI.Model.RoleRepresentation.t]): 
  - opts (KeywordList): [optional] Optional parameters
  ## Returns

  {:ok, nil} on success
  {:error, Tesla.Env.t} on failure
  """
  @spec realm_groups_id_role_mappings_clients_client_post(Tesla.Env.client, String.t, String.t, String.t, list(KeycloakAdminRESTAPI.Model.RoleRepresentation.t), keyword()) :: {:ok, nil} | {:error, Tesla.Env.t}
  def realm_groups_id_role_mappings_clients_client_post(connection, realm, id, client, role_representation, _opts \\ []) do
    %{}
    |> method(:post)
    |> url("/#{realm}/groups/#{id}/role-mappings/clients/#{client}")
    |> add_param(:body, :body, role_representation)
    |> Enum.into([])
    |> (&Connection.request(connection, &1)).()
    |> evaluate_response([
      { "2XX", false}
    ])
  end

  @doc """
  Get available client-level roles that can be mapped to the user

  ## Parameters

  - connection (KeycloakAdminRESTAPI.Connection): Connection to server
  - realm (String.t): realm name (not id!)
  - id (String.t): User id
  - client (String.t): 
  - opts (KeywordList): [optional] Optional parameters
  ## Returns

  {:ok, [%Map{}, ...]} on success
  {:error, Tesla.Env.t} on failure
  """
  @spec realm_users_id_role_mappings_clients_client_available_get(Tesla.Env.client, String.t, String.t, String.t, keyword()) :: {:ok, list(Map.t)} | {:error, Tesla.Env.t}
  def realm_users_id_role_mappings_clients_client_available_get(connection, realm, id, client, _opts \\ []) do
    %{}
    |> method(:get)
    |> url("/#{realm}/users/#{id}/role-mappings/clients/#{client}/available")
    |> Enum.into([])
    |> (&Connection.request(connection, &1)).()
    |> evaluate_response([
      { "2XX", []}
    ])
  end

  @doc """
  Get effective client-level role mappings   This recurses any composite roles

  ## Parameters

  - connection (KeycloakAdminRESTAPI.Connection): Connection to server
  - realm (String.t): realm name (not id!)
  - id (String.t): User id
  - client (String.t): 
  - opts (KeywordList): [optional] Optional parameters
    - :brief_representation (boolean()): if false, return roles with their attributes
  ## Returns

  {:ok, [%Map{}, ...]} on success
  {:error, Tesla.Env.t} on failure
  """
  @spec realm_users_id_role_mappings_clients_client_composite_get(Tesla.Env.client, String.t, String.t, String.t, keyword()) :: {:ok, list(Map.t)} | {:error, Tesla.Env.t}
  def realm_users_id_role_mappings_clients_client_composite_get(connection, realm, id, client, opts \\ []) do
    optional_params = %{
      :"briefRepresentation" => :query
    }
    %{}
    |> method(:get)
    |> url("/#{realm}/users/#{id}/role-mappings/clients/#{client}/composite")
    |> add_optional_params(optional_params, opts)
    |> Enum.into([])
    |> (&Connection.request(connection, &1)).()
    |> evaluate_response([
      { "2XX", []}
    ])
  end

  @doc """
  Delete client-level roles from user role mapping

  ## Parameters

  - connection (KeycloakAdminRESTAPI.Connection): Connection to server
  - realm (String.t): realm name (not id!)
  - id (String.t): User id
  - client (String.t): 
  - role_representation ([KeycloakAdminRESTAPI.Model.RoleRepresentation.t]): 
  - opts (KeywordList): [optional] Optional parameters
  ## Returns

  {:ok, nil} on success
  {:error, Tesla.Env.t} on failure
  """
  @spec realm_users_id_role_mappings_clients_client_delete(Tesla.Env.client, String.t, String.t, String.t, list(KeycloakAdminRESTAPI.Model.RoleRepresentation.t), keyword()) :: {:ok, nil} | {:error, Tesla.Env.t}
  def realm_users_id_role_mappings_clients_client_delete(connection, realm, id, client, role_representation, _opts \\ []) do
    %{}
    |> method(:delete)
    |> url("/#{realm}/users/#{id}/role-mappings/clients/#{client}")
    |> add_param(:body, :body, role_representation)
    |> Enum.into([])
    |> (&Connection.request(connection, &1)).()
    |> evaluate_response([
      { "2XX", false}
    ])
  end

  @doc """
  Get client-level role mappings for the user, and the app

  ## Parameters

  - connection (KeycloakAdminRESTAPI.Connection): Connection to server
  - realm (String.t): realm name (not id!)
  - id (String.t): User id
  - client (String.t): 
  - opts (KeywordList): [optional] Optional parameters
  ## Returns

  {:ok, [%Map{}, ...]} on success
  {:error, Tesla.Env.t} on failure
  """
  @spec realm_users_id_role_mappings_clients_client_get(Tesla.Env.client, String.t, String.t, String.t, keyword()) :: {:ok, list(Map.t)} | {:error, Tesla.Env.t}
  def realm_users_id_role_mappings_clients_client_get(connection, realm, id, client, _opts \\ []) do
    %{}
    |> method(:get)
    |> url("/#{realm}/users/#{id}/role-mappings/clients/#{client}")
    |> Enum.into([])
    |> (&Connection.request(connection, &1)).()
    |> evaluate_response([
      { "2XX", []}
    ])
  end

  @doc """
  Add client-level roles to the user role mapping

  ## Parameters

  - connection (KeycloakAdminRESTAPI.Connection): Connection to server
  - realm (String.t): realm name (not id!)
  - id (String.t): User id
  - client (String.t): 
  - role_representation ([KeycloakAdminRESTAPI.Model.RoleRepresentation.t]): 
  - opts (KeywordList): [optional] Optional parameters
  ## Returns

  {:ok, nil} on success
  {:error, Tesla.Env.t} on failure
  """
  @spec realm_users_id_role_mappings_clients_client_post(Tesla.Env.client, String.t, String.t, String.t, list(KeycloakAdminRESTAPI.Model.RoleRepresentation.t), keyword()) :: {:ok, nil} | {:error, Tesla.Env.t}
  def realm_users_id_role_mappings_clients_client_post(connection, realm, id, client, role_representation, _opts \\ []) do
    %{}
    |> method(:post)
    |> url("/#{realm}/users/#{id}/role-mappings/clients/#{client}")
    |> add_param(:body, :body, role_representation)
    |> Enum.into([])
    |> (&Connection.request(connection, &1)).()
    |> evaluate_response([
      { "2XX", false}
    ])
  end
end
