# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule KeycloakAdminRESTAPI.Api.Key do
  @moduledoc """
  API calls for all endpoints tagged `Key`.
  """

  alias KeycloakAdminRESTAPI.Connection
  import KeycloakAdminRESTAPI.RequestBuilder


  @doc """

  ## Parameters

  - connection (KeycloakAdminRESTAPI.Connection): Connection to server
  - realm (String.t): realm name (not id!)
  - opts (KeywordList): [optional] Optional parameters
  ## Returns

  {:ok, KeycloakAdminRESTAPI.Model.KeysMetadataRepresentation.t} on success
  {:error, Tesla.Env.t} on failure
  """
  @spec realm_keys_get(Tesla.Env.client, String.t, keyword()) :: {:ok, KeycloakAdminRESTAPI.Model.KeysMetadataRepresentation.t} | {:error, Tesla.Env.t}
  def realm_keys_get(connection, realm, _opts \\ []) do
    %{}
    |> method(:get)
    |> url("/#{realm}/keys")
    |> Enum.into([])
    |> (&Connection.request(connection, &1)).()
    |> evaluate_response([
      { "2XX", %KeycloakAdminRESTAPI.Model.KeysMetadataRepresentation{}}
    ])
  end
end
