# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule KeycloakAdminRESTAPI.Api.ScopeMappings do
  @moduledoc """
  API calls for all endpoints tagged `ScopeMappings`.
  """

  alias KeycloakAdminRESTAPI.Connection
  import KeycloakAdminRESTAPI.RequestBuilder


  @doc """
  The available client-level roles   Returns the roles for the client that can be associated with the client’s scope

  ## Parameters

  - connection (KeycloakAdminRESTAPI.Connection): Connection to server
  - realm (String.t): realm name (not id!)
  - id (String.t): id of client scope (not name)
  - client (String.t): 
  - opts (KeywordList): [optional] Optional parameters
  ## Returns

  {:ok, [%Map{}, ...]} on success
  {:error, Tesla.Env.t} on failure
  """
  @spec realm_client_scopes_id_scope_mappings_clients_client_available_get(Tesla.Env.client, String.t, String.t, String.t, keyword()) :: {:ok, list(Map.t)} | {:error, Tesla.Env.t}
  def realm_client_scopes_id_scope_mappings_clients_client_available_get(connection, realm, id, client, _opts \\ []) do
    %{}
    |> method(:get)
    |> url("/#{realm}/client-scopes/#{id}/scope-mappings/clients/#{client}/available")
    |> Enum.into([])
    |> (&Connection.request(connection, &1)).()
    |> evaluate_response([
      { "2XX", []}
    ])
  end

  @doc """
  Get effective client roles   Returns the roles for the client that are associated with the client’s scope.

  ## Parameters

  - connection (KeycloakAdminRESTAPI.Connection): Connection to server
  - realm (String.t): realm name (not id!)
  - id (String.t): id of client scope (not name)
  - client (String.t): 
  - opts (KeywordList): [optional] Optional parameters
    - :brief_representation (boolean()): if false, return roles with their attributes
  ## Returns

  {:ok, [%Map{}, ...]} on success
  {:error, Tesla.Env.t} on failure
  """
  @spec realm_client_scopes_id_scope_mappings_clients_client_composite_get(Tesla.Env.client, String.t, String.t, String.t, keyword()) :: {:ok, list(Map.t)} | {:error, Tesla.Env.t}
  def realm_client_scopes_id_scope_mappings_clients_client_composite_get(connection, realm, id, client, opts \\ []) do
    optional_params = %{
      :"briefRepresentation" => :query
    }
    %{}
    |> method(:get)
    |> url("/#{realm}/client-scopes/#{id}/scope-mappings/clients/#{client}/composite")
    |> add_optional_params(optional_params, opts)
    |> Enum.into([])
    |> (&Connection.request(connection, &1)).()
    |> evaluate_response([
      { "2XX", []}
    ])
  end

  @doc """
  Remove client-level roles from the client’s scope.

  ## Parameters

  - connection (KeycloakAdminRESTAPI.Connection): Connection to server
  - realm (String.t): realm name (not id!)
  - id (String.t): id of client scope (not name)
  - client (String.t): 
  - role_representation ([KeycloakAdminRESTAPI.Model.RoleRepresentation.t]): 
  - opts (KeywordList): [optional] Optional parameters
  ## Returns

  {:ok, nil} on success
  {:error, Tesla.Env.t} on failure
  """
  @spec realm_client_scopes_id_scope_mappings_clients_client_delete(Tesla.Env.client, String.t, String.t, String.t, list(KeycloakAdminRESTAPI.Model.RoleRepresentation.t), keyword()) :: {:ok, nil} | {:error, Tesla.Env.t}
  def realm_client_scopes_id_scope_mappings_clients_client_delete(connection, realm, id, client, role_representation, _opts \\ []) do
    %{}
    |> method(:delete)
    |> url("/#{realm}/client-scopes/#{id}/scope-mappings/clients/#{client}")
    |> add_param(:body, :body, role_representation)
    |> Enum.into([])
    |> (&Connection.request(connection, &1)).()
    |> evaluate_response([
      { "2XX", false}
    ])
  end

  @doc """
  Get the roles associated with a client’s scope   Returns roles for the client.

  ## Parameters

  - connection (KeycloakAdminRESTAPI.Connection): Connection to server
  - realm (String.t): realm name (not id!)
  - id (String.t): id of client scope (not name)
  - client (String.t): 
  - opts (KeywordList): [optional] Optional parameters
  ## Returns

  {:ok, [%Map{}, ...]} on success
  {:error, Tesla.Env.t} on failure
  """
  @spec realm_client_scopes_id_scope_mappings_clients_client_get(Tesla.Env.client, String.t, String.t, String.t, keyword()) :: {:ok, list(Map.t)} | {:error, Tesla.Env.t}
  def realm_client_scopes_id_scope_mappings_clients_client_get(connection, realm, id, client, _opts \\ []) do
    %{}
    |> method(:get)
    |> url("/#{realm}/client-scopes/#{id}/scope-mappings/clients/#{client}")
    |> Enum.into([])
    |> (&Connection.request(connection, &1)).()
    |> evaluate_response([
      { "2XX", []}
    ])
  end

  @doc """
  Add client-level roles to the client’s scope

  ## Parameters

  - connection (KeycloakAdminRESTAPI.Connection): Connection to server
  - realm (String.t): realm name (not id!)
  - id (String.t): id of client scope (not name)
  - client (String.t): 
  - role_representation ([KeycloakAdminRESTAPI.Model.RoleRepresentation.t]): 
  - opts (KeywordList): [optional] Optional parameters
  ## Returns

  {:ok, nil} on success
  {:error, Tesla.Env.t} on failure
  """
  @spec realm_client_scopes_id_scope_mappings_clients_client_post(Tesla.Env.client, String.t, String.t, String.t, list(KeycloakAdminRESTAPI.Model.RoleRepresentation.t), keyword()) :: {:ok, nil} | {:error, Tesla.Env.t}
  def realm_client_scopes_id_scope_mappings_clients_client_post(connection, realm, id, client, role_representation, _opts \\ []) do
    %{}
    |> method(:post)
    |> url("/#{realm}/client-scopes/#{id}/scope-mappings/clients/#{client}")
    |> add_param(:body, :body, role_representation)
    |> Enum.into([])
    |> (&Connection.request(connection, &1)).()
    |> evaluate_response([
      { "2XX", false}
    ])
  end

  @doc """
  Get realm-level roles that are available to attach to this client’s scope

  ## Parameters

  - connection (KeycloakAdminRESTAPI.Connection): Connection to server
  - realm (String.t): realm name (not id!)
  - id (String.t): id of client scope (not name)
  - opts (KeywordList): [optional] Optional parameters
  ## Returns

  {:ok, [%Map{}, ...]} on success
  {:error, Tesla.Env.t} on failure
  """
  @spec realm_client_scopes_id_scope_mappings_realm_available_get(Tesla.Env.client, String.t, String.t, keyword()) :: {:ok, list(Map.t)} | {:error, Tesla.Env.t}
  def realm_client_scopes_id_scope_mappings_realm_available_get(connection, realm, id, _opts \\ []) do
    %{}
    |> method(:get)
    |> url("/#{realm}/client-scopes/#{id}/scope-mappings/realm/available")
    |> Enum.into([])
    |> (&Connection.request(connection, &1)).()
    |> evaluate_response([
      { "2XX", []}
    ])
  end

  @doc """
  Get effective realm-level roles associated with the client’s scope   What this does is recurse  any composite roles associated with the client’s scope and adds the roles to this lists.

  ## Parameters

  - connection (KeycloakAdminRESTAPI.Connection): Connection to server
  - realm (String.t): realm name (not id!)
  - id (String.t): id of client scope (not name)
  - opts (KeywordList): [optional] Optional parameters
    - :brief_representation (boolean()): if false, return roles with their attributes
  ## Returns

  {:ok, [%Map{}, ...]} on success
  {:error, Tesla.Env.t} on failure
  """
  @spec realm_client_scopes_id_scope_mappings_realm_composite_get(Tesla.Env.client, String.t, String.t, keyword()) :: {:ok, list(Map.t)} | {:error, Tesla.Env.t}
  def realm_client_scopes_id_scope_mappings_realm_composite_get(connection, realm, id, opts \\ []) do
    optional_params = %{
      :"briefRepresentation" => :query
    }
    %{}
    |> method(:get)
    |> url("/#{realm}/client-scopes/#{id}/scope-mappings/realm/composite")
    |> add_optional_params(optional_params, opts)
    |> Enum.into([])
    |> (&Connection.request(connection, &1)).()
    |> evaluate_response([
      { "2XX", []}
    ])
  end

  @doc """
  Remove a set of realm-level roles from the client’s scope

  ## Parameters

  - connection (KeycloakAdminRESTAPI.Connection): Connection to server
  - realm (String.t): realm name (not id!)
  - id (String.t): id of client scope (not name)
  - role_representation ([KeycloakAdminRESTAPI.Model.RoleRepresentation.t]): 
  - opts (KeywordList): [optional] Optional parameters
  ## Returns

  {:ok, nil} on success
  {:error, Tesla.Env.t} on failure
  """
  @spec realm_client_scopes_id_scope_mappings_realm_delete(Tesla.Env.client, String.t, String.t, list(KeycloakAdminRESTAPI.Model.RoleRepresentation.t), keyword()) :: {:ok, nil} | {:error, Tesla.Env.t}
  def realm_client_scopes_id_scope_mappings_realm_delete(connection, realm, id, role_representation, _opts \\ []) do
    %{}
    |> method(:delete)
    |> url("/#{realm}/client-scopes/#{id}/scope-mappings/realm")
    |> add_param(:body, :body, role_representation)
    |> Enum.into([])
    |> (&Connection.request(connection, &1)).()
    |> evaluate_response([
      { "2XX", false}
    ])
  end

  @doc """
  Get realm-level roles associated with the client’s scope

  ## Parameters

  - connection (KeycloakAdminRESTAPI.Connection): Connection to server
  - realm (String.t): realm name (not id!)
  - id (String.t): id of client scope (not name)
  - opts (KeywordList): [optional] Optional parameters
  ## Returns

  {:ok, [%Map{}, ...]} on success
  {:error, Tesla.Env.t} on failure
  """
  @spec realm_client_scopes_id_scope_mappings_realm_get(Tesla.Env.client, String.t, String.t, keyword()) :: {:ok, list(Map.t)} | {:error, Tesla.Env.t}
  def realm_client_scopes_id_scope_mappings_realm_get(connection, realm, id, _opts \\ []) do
    %{}
    |> method(:get)
    |> url("/#{realm}/client-scopes/#{id}/scope-mappings/realm")
    |> Enum.into([])
    |> (&Connection.request(connection, &1)).()
    |> evaluate_response([
      { "2XX", []}
    ])
  end

  @doc """
  Add a set of realm-level roles to the client’s scope

  ## Parameters

  - connection (KeycloakAdminRESTAPI.Connection): Connection to server
  - realm (String.t): realm name (not id!)
  - id (String.t): id of client scope (not name)
  - role_representation ([KeycloakAdminRESTAPI.Model.RoleRepresentation.t]): 
  - opts (KeywordList): [optional] Optional parameters
  ## Returns

  {:ok, nil} on success
  {:error, Tesla.Env.t} on failure
  """
  @spec realm_client_scopes_id_scope_mappings_realm_post(Tesla.Env.client, String.t, String.t, list(KeycloakAdminRESTAPI.Model.RoleRepresentation.t), keyword()) :: {:ok, nil} | {:error, Tesla.Env.t}
  def realm_client_scopes_id_scope_mappings_realm_post(connection, realm, id, role_representation, _opts \\ []) do
    %{}
    |> method(:post)
    |> url("/#{realm}/client-scopes/#{id}/scope-mappings/realm")
    |> add_param(:body, :body, role_representation)
    |> Enum.into([])
    |> (&Connection.request(connection, &1)).()
    |> evaluate_response([
      { "2XX", false}
    ])
  end

  @doc """
  The available client-level roles   Returns the roles for the client that can be associated with the client’s scope

  ## Parameters

  - connection (KeycloakAdminRESTAPI.Connection): Connection to server
  - realm (String.t): realm name (not id!)
  - id (String.t): id of client (not client-id)
  - client (String.t): 
  - opts (KeywordList): [optional] Optional parameters
  ## Returns

  {:ok, [%Map{}, ...]} on success
  {:error, Tesla.Env.t} on failure
  """
  @spec realm_clients_id_scope_mappings_clients_client_available_get(Tesla.Env.client, String.t, String.t, String.t, keyword()) :: {:ok, list(Map.t)} | {:error, Tesla.Env.t}
  def realm_clients_id_scope_mappings_clients_client_available_get(connection, realm, id, client, _opts \\ []) do
    %{}
    |> method(:get)
    |> url("/#{realm}/clients/#{id}/scope-mappings/clients/#{client}/available")
    |> Enum.into([])
    |> (&Connection.request(connection, &1)).()
    |> evaluate_response([
      { "2XX", []}
    ])
  end

  @doc """
  Get effective client roles   Returns the roles for the client that are associated with the client’s scope.

  ## Parameters

  - connection (KeycloakAdminRESTAPI.Connection): Connection to server
  - realm (String.t): realm name (not id!)
  - id (String.t): id of client (not client-id)
  - client (String.t): 
  - opts (KeywordList): [optional] Optional parameters
    - :brief_representation (boolean()): if false, return roles with their attributes
  ## Returns

  {:ok, [%Map{}, ...]} on success
  {:error, Tesla.Env.t} on failure
  """
  @spec realm_clients_id_scope_mappings_clients_client_composite_get(Tesla.Env.client, String.t, String.t, String.t, keyword()) :: {:ok, list(Map.t)} | {:error, Tesla.Env.t}
  def realm_clients_id_scope_mappings_clients_client_composite_get(connection, realm, id, client, opts \\ []) do
    optional_params = %{
      :"briefRepresentation" => :query
    }
    %{}
    |> method(:get)
    |> url("/#{realm}/clients/#{id}/scope-mappings/clients/#{client}/composite")
    |> add_optional_params(optional_params, opts)
    |> Enum.into([])
    |> (&Connection.request(connection, &1)).()
    |> evaluate_response([
      { "2XX", []}
    ])
  end

  @doc """
  Remove client-level roles from the client’s scope.

  ## Parameters

  - connection (KeycloakAdminRESTAPI.Connection): Connection to server
  - realm (String.t): realm name (not id!)
  - id (String.t): id of client (not client-id)
  - client (String.t): 
  - role_representation ([KeycloakAdminRESTAPI.Model.RoleRepresentation.t]): 
  - opts (KeywordList): [optional] Optional parameters
  ## Returns

  {:ok, nil} on success
  {:error, Tesla.Env.t} on failure
  """
  @spec realm_clients_id_scope_mappings_clients_client_delete(Tesla.Env.client, String.t, String.t, String.t, list(KeycloakAdminRESTAPI.Model.RoleRepresentation.t), keyword()) :: {:ok, nil} | {:error, Tesla.Env.t}
  def realm_clients_id_scope_mappings_clients_client_delete(connection, realm, id, client, role_representation, _opts \\ []) do
    %{}
    |> method(:delete)
    |> url("/#{realm}/clients/#{id}/scope-mappings/clients/#{client}")
    |> add_param(:body, :body, role_representation)
    |> Enum.into([])
    |> (&Connection.request(connection, &1)).()
    |> evaluate_response([
      { "2XX", false}
    ])
  end

  @doc """
  Get the roles associated with a client’s scope   Returns roles for the client.

  ## Parameters

  - connection (KeycloakAdminRESTAPI.Connection): Connection to server
  - realm (String.t): realm name (not id!)
  - id (String.t): id of client (not client-id)
  - client (String.t): 
  - opts (KeywordList): [optional] Optional parameters
  ## Returns

  {:ok, [%Map{}, ...]} on success
  {:error, Tesla.Env.t} on failure
  """
  @spec realm_clients_id_scope_mappings_clients_client_get(Tesla.Env.client, String.t, String.t, String.t, keyword()) :: {:ok, list(Map.t)} | {:error, Tesla.Env.t}
  def realm_clients_id_scope_mappings_clients_client_get(connection, realm, id, client, _opts \\ []) do
    %{}
    |> method(:get)
    |> url("/#{realm}/clients/#{id}/scope-mappings/clients/#{client}")
    |> Enum.into([])
    |> (&Connection.request(connection, &1)).()
    |> evaluate_response([
      { "2XX", []}
    ])
  end

  @doc """
  Add client-level roles to the client’s scope

  ## Parameters

  - connection (KeycloakAdminRESTAPI.Connection): Connection to server
  - realm (String.t): realm name (not id!)
  - id (String.t): id of client (not client-id)
  - client (String.t): 
  - role_representation ([KeycloakAdminRESTAPI.Model.RoleRepresentation.t]): 
  - opts (KeywordList): [optional] Optional parameters
  ## Returns

  {:ok, nil} on success
  {:error, Tesla.Env.t} on failure
  """
  @spec realm_clients_id_scope_mappings_clients_client_post(Tesla.Env.client, String.t, String.t, String.t, list(KeycloakAdminRESTAPI.Model.RoleRepresentation.t), keyword()) :: {:ok, nil} | {:error, Tesla.Env.t}
  def realm_clients_id_scope_mappings_clients_client_post(connection, realm, id, client, role_representation, _opts \\ []) do
    %{}
    |> method(:post)
    |> url("/#{realm}/clients/#{id}/scope-mappings/clients/#{client}")
    |> add_param(:body, :body, role_representation)
    |> Enum.into([])
    |> (&Connection.request(connection, &1)).()
    |> evaluate_response([
      { "2XX", false}
    ])
  end

  @doc """
  Get realm-level roles that are available to attach to this client’s scope

  ## Parameters

  - connection (KeycloakAdminRESTAPI.Connection): Connection to server
  - realm (String.t): realm name (not id!)
  - id (String.t): id of client (not client-id)
  - opts (KeywordList): [optional] Optional parameters
  ## Returns

  {:ok, [%Map{}, ...]} on success
  {:error, Tesla.Env.t} on failure
  """
  @spec realm_clients_id_scope_mappings_realm_available_get(Tesla.Env.client, String.t, String.t, keyword()) :: {:ok, list(Map.t)} | {:error, Tesla.Env.t}
  def realm_clients_id_scope_mappings_realm_available_get(connection, realm, id, _opts \\ []) do
    %{}
    |> method(:get)
    |> url("/#{realm}/clients/#{id}/scope-mappings/realm/available")
    |> Enum.into([])
    |> (&Connection.request(connection, &1)).()
    |> evaluate_response([
      { "2XX", []}
    ])
  end

  @doc """
  Get effective realm-level roles associated with the client’s scope   What this does is recurse  any composite roles associated with the client’s scope and adds the roles to this lists.

  ## Parameters

  - connection (KeycloakAdminRESTAPI.Connection): Connection to server
  - realm (String.t): realm name (not id!)
  - id (String.t): id of client (not client-id)
  - opts (KeywordList): [optional] Optional parameters
    - :brief_representation (boolean()): if false, return roles with their attributes
  ## Returns

  {:ok, [%Map{}, ...]} on success
  {:error, Tesla.Env.t} on failure
  """
  @spec realm_clients_id_scope_mappings_realm_composite_get(Tesla.Env.client, String.t, String.t, keyword()) :: {:ok, list(Map.t)} | {:error, Tesla.Env.t}
  def realm_clients_id_scope_mappings_realm_composite_get(connection, realm, id, opts \\ []) do
    optional_params = %{
      :"briefRepresentation" => :query
    }
    %{}
    |> method(:get)
    |> url("/#{realm}/clients/#{id}/scope-mappings/realm/composite")
    |> add_optional_params(optional_params, opts)
    |> Enum.into([])
    |> (&Connection.request(connection, &1)).()
    |> evaluate_response([
      { "2XX", []}
    ])
  end

  @doc """
  Remove a set of realm-level roles from the client’s scope

  ## Parameters

  - connection (KeycloakAdminRESTAPI.Connection): Connection to server
  - realm (String.t): realm name (not id!)
  - id (String.t): id of client (not client-id)
  - role_representation ([KeycloakAdminRESTAPI.Model.RoleRepresentation.t]): 
  - opts (KeywordList): [optional] Optional parameters
  ## Returns

  {:ok, nil} on success
  {:error, Tesla.Env.t} on failure
  """
  @spec realm_clients_id_scope_mappings_realm_delete(Tesla.Env.client, String.t, String.t, list(KeycloakAdminRESTAPI.Model.RoleRepresentation.t), keyword()) :: {:ok, nil} | {:error, Tesla.Env.t}
  def realm_clients_id_scope_mappings_realm_delete(connection, realm, id, role_representation, _opts \\ []) do
    %{}
    |> method(:delete)
    |> url("/#{realm}/clients/#{id}/scope-mappings/realm")
    |> add_param(:body, :body, role_representation)
    |> Enum.into([])
    |> (&Connection.request(connection, &1)).()
    |> evaluate_response([
      { "2XX", false}
    ])
  end

  @doc """
  Get realm-level roles associated with the client’s scope

  ## Parameters

  - connection (KeycloakAdminRESTAPI.Connection): Connection to server
  - realm (String.t): realm name (not id!)
  - id (String.t): id of client (not client-id)
  - opts (KeywordList): [optional] Optional parameters
  ## Returns

  {:ok, [%Map{}, ...]} on success
  {:error, Tesla.Env.t} on failure
  """
  @spec realm_clients_id_scope_mappings_realm_get(Tesla.Env.client, String.t, String.t, keyword()) :: {:ok, list(Map.t)} | {:error, Tesla.Env.t}
  def realm_clients_id_scope_mappings_realm_get(connection, realm, id, _opts \\ []) do
    %{}
    |> method(:get)
    |> url("/#{realm}/clients/#{id}/scope-mappings/realm")
    |> Enum.into([])
    |> (&Connection.request(connection, &1)).()
    |> evaluate_response([
      { "2XX", []}
    ])
  end

  @doc """
  Add a set of realm-level roles to the client’s scope

  ## Parameters

  - connection (KeycloakAdminRESTAPI.Connection): Connection to server
  - realm (String.t): realm name (not id!)
  - id (String.t): id of client (not client-id)
  - role_representation ([KeycloakAdminRESTAPI.Model.RoleRepresentation.t]): 
  - opts (KeywordList): [optional] Optional parameters
  ## Returns

  {:ok, nil} on success
  {:error, Tesla.Env.t} on failure
  """
  @spec realm_clients_id_scope_mappings_realm_post(Tesla.Env.client, String.t, String.t, list(KeycloakAdminRESTAPI.Model.RoleRepresentation.t), keyword()) :: {:ok, nil} | {:error, Tesla.Env.t}
  def realm_clients_id_scope_mappings_realm_post(connection, realm, id, role_representation, _opts \\ []) do
    %{}
    |> method(:post)
    |> url("/#{realm}/clients/#{id}/scope-mappings/realm")
    |> add_param(:body, :body, role_representation)
    |> Enum.into([])
    |> (&Connection.request(connection, &1)).()
    |> evaluate_response([
      { "2XX", false}
    ])
  end
end
